apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tj17
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: tj17
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
  - name: foo
    valueFrom: 
      secretKeyRef:
        name: my-secret
        key: foo
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tfynes-pivotal/tj17
      ref:
        branch: main
